[package]
name = "weights"
version = "0.1.0"
authors = ["Anonymous"]
edition = "2018"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'support/std',
    'system/std',
    'balances/std',
    'runtime-primitives/std',
]

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.0.6'

[dependencies.support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
rev = 'ba5c85add52897acbd98f382ae11f7a11583e322'

[dependencies.system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = 'ba5c85add52897acbd98f382ae11f7a11583e322'

[dependencies.balances]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
rev = 'ba5c85add52897acbd98f382ae11f7a11583e322'

[dependencies.runtime-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-runtime'
rev = 'ba5c85add52897acbd98f382ae11f7a11583e322'

[dev-dependencies.primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-core'
rev = 'ba5c85add52897acbd98f382ae11f7a11583e322'
