[package]
name = "sum-storage-rpc-runtime-api"
version = "2.0.0"
authors = ["Joshy Orndorff"]
edition = "2018"

[dependencies]
sp-api = { rev = '0bd9ffacdeb9bf3c97c04114de2cca5490ee98b6', git = 'https://github.com/paritytech/substrate.git', default_features = false}

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
	"sp-api/std",
]
