[package]
authors = ['Joshy Orndorff, Wei Tang']
edition = '2018'
homepage = 'https://substrate.dev/recipes'
name = 'sha3pow'
repository = 'https://github.com/substrate-developer-hub/recipes'
version = "2.0.0-alpha.6"
description = 'Sha3-based Proof of Work algorithms for Substrate'

[dependencies]
parity-scale-codec = '1.3.0'
sha3 = "0.8"
rand = { version = "0.7", features = ["small_rng"] }
sc-consensus-pow = { git = 'https://github.com/paritytech/substrate', branch = 'joshy-pow-import-justification' }
sp-api = { git = 'https://github.com/paritytech/substrate', branch = 'joshy-pow-import-justification' }
sp-consensus-pow = { git = 'https://github.com/paritytech/substrate', branch = 'joshy-pow-import-justification' }
sp-core = { git = 'https://github.com/paritytech/substrate', branch = 'joshy-pow-import-justification' }
sp-runtime = { git = 'https://github.com/paritytech/substrate', branch = 'joshy-pow-import-justification' }
