[package]
name = "weight-fee-runtime"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
safe-mix = { version = "1.0", default-features = false }
weights = { path = "../../pallets/weights", default-features = false }

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.0.6'

[dependencies.rstd]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = "sp-std"
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.runtime-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-io'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.version]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-version'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.substrate-session]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-session'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.balances]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.generic-asset]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-generic-asset'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.transaction-payment]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-transaction-payment'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.babe]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-babe'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.sp-consensus-babe]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.executive]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-executive'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.indices]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-indices'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.grandpa]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-grandpa'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.randomness-collective-flip]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-randomness-collective-flip'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.timestamp]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-timestamp'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.sudo]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-sudo'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-runtime'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.sp-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.block-builder-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-block-builder'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.sp-transaction-pool]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.inherents]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-inherents'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'

[dependencies.offchain-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-offchain'
rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630'


[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	"babe/std",
	"balances/std",
	"block-builder-api/std",
	"executive/std",
	"generic-asset/std",
	"grandpa/std",
	"indices/std",
	"inherents/std",
	"offchain-primitives/std",
	"parity-scale-codec/std",
	"randomness-collective-flip/std",
	"rstd/std",
	"runtime-io/std",
	"safe-mix/std",
	"serde",
	"sp-api/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-runtime/std",
	"substrate-session/std",
	"sudo/std",
	"support/std",
	"system/std",
	"timestamp/std",
	"transaction-payment/std",
	"version/std",
	"weights/std",
  "sp-transaction-pool/std",
]
