[package]
name = "child-trie"
version = "0.1.0"
authors = ["4meta5"]
edition = "2018"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'support/std',
    'system/std',
    'runtime-primitives/std',
]


[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.0.6'

[dependencies.support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
rev = '68e51d6e24862d499b5f042321cc87b172579e74'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = '68e51d6e24862d499b5f042321cc87b172579e74'

[dependencies.runtime-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-runtime'
rev = '68e51d6e24862d499b5f042321cc87b172579e74'

[dependencies.rstd]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-std'
rev = '68e51d6e24862d499b5f042321cc87b172579e74'

[dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-core'
rev = '68e51d6e24862d499b5f042321cc87b172579e74'
