[package]
name = "frameless-runtime"
version = "2.0.0"
authors = ["Joshy Orndorff"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
safe-mix = { version = "1.0", default-features = false }

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.0.6'

[dependencies.rstd]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = "sp-std"
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sp-consensus-aura]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.version]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-version'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-core'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-runtime'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sp-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sp-session]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.block-builder-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-block-builder'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sp-finality-grandpa]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sp-transaction-pool]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.inherents]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-inherents'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.offchain-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-offchain'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	# Substrate dependencies alphabetically
	"block-builder-api/std",
	"inherents/std",
	"offchain-primitives/std",
	"parity-scale-codec/std",
	"primitives/std",
	"rstd/std",
	"safe-mix/std",
	"serde",
	"sp-api/std",
	"sp-consensus-aura/std",
	"sp-session/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-finality-grandpa/std",
	"sp-transaction-pool/std",
	"version/std",
]
