[package]
name = "frameless-runtime"
version = "2.0.0"
authors = ["Joshy Orndorff"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.3.0'

[dependencies.rstd]
default-features = false
package = "sp-std"
version = '2.0.0-alpha.5'

[dependencies.sp-consensus-aura]
default-features = false
version = '0.8.0-alpha.5'

[dependencies.sp-io]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-version]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.primitives]
default-features = false
package = 'sp-core'
version = '2.0.0-alpha.5'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-api]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-session]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.block-builder-api]
default-features = false
package = 'sp-block-builder'
version = '2.0.0-alpha.5'

[dependencies.sp-finality-grandpa]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-transaction-pool]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.inherents]
default-features = false
package = 'sp-inherents'
version = '2.0.0-alpha.5'

[dependencies.offchain-primitives]
default-features = false
package = 'sp-offchain'
version = '2.0.0-alpha.5'

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	# Substrate dependencies alphabetically
	"block-builder-api/std",
	"inherents/std",
	"offchain-primitives/std",
	"parity-scale-codec/std",
	"primitives/std",
	"rstd/std",
	"serde",
	"sp-api/std",
	"sp-consensus-aura/std",
	"sp-session/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-finality-grandpa/std",
	"sp-transaction-pool/std",
	"sp-version/std",
]
