[package]
name = "sum-storage-rpc"
version = "2.0.0"
authors = ["JoshyOrndorff"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0" }
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
serde = { version = "1.0.101", features = ["derive"], optional = true }

sp-rpc = { rev = '68e51d6e24862d499b5f042321cc87b172579e74', git = 'https://github.com/paritytech/substrate.git', default_features = false}
sp-runtime = { rev = '68e51d6e24862d499b5f042321cc87b172579e74', git = 'https://github.com/paritytech/substrate.git', default_features = false}
sp-blockchain = { rev = '68e51d6e24862d499b5f042321cc87b172579e74', git = 'https://github.com/paritytech/substrate.git', default_features = false}
sp-api = { rev = '68e51d6e24862d499b5f042321cc87b172579e74', git = 'https://github.com/paritytech/substrate.git', default_features = false }

sum-storage-rpc-runtime-api = { version = "2.0.0", path = "./runtime-api", default_features = false }

[features]
default = ["std"]
std = [
  "serde",
  "sp-runtime/std",
  "sp-api/std",
  "sum-storage-rpc-runtime-api/std"
]
