[package]
name = "super-runtime"
version = "2.0.0"
authors = ["Joshy Orndorff"]
edition = "2018"

[dependencies]
parity-scale-codec = { version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", optional = true, features = ["derive"] }
safe-mix = { version = "1.0", default-features = false }
# Substrate Pallets
babe = { package = 'pallet-babe', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', git = 'https://github.com/paritytech/substrate.git', default_features = false}
balances = { package = 'pallet-balances', git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
grandpa = { package = 'pallet-grandpa', git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
randomness-collective-flip = { package = 'pallet-randomness-collective-flip', git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
sudo = { package = 'pallet-sudo', git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
transaction-payment = { package = 'pallet-transaction-payment', git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
timestamp = { package = 'pallet-timestamp', git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }

# Recipe Pallets
adding-machine = { path = "../../pallets/adding-machine", default-features = false }
basic-token = { path = "../../pallets/basic-token", default-features = false }
charity = { path = "../../pallets/charity", default-features = false }
check-membership = { path = "../../pallets/check-membership", default-features = false }
compounding-interest = { path = "../../pallets/compounding-interest", default-features = false }
constant-config = { path = "../../pallets/constant-config", default-features = false }
default-instance = { path = "../../pallets/default-instance", default-features = false }
double-map = { path = "../../pallets/double-map", default-features = false }
execution-schedule = { path = "../../pallets/execution-schedule", default-features = false }
fixed-point = { path = "../../pallets/fixed-point", default-features = false }
generic-event = { path = "../../pallets/generic-event", default-features = false }
hello-substrate = { path = "../../pallets/hello-substrate", default-features = false }
last-caller = { path = "../../pallets/last-caller", default-features = false }
ringbuffer-queue = { path = "../../pallets/ringbuffer-queue", default_features = false }
randomness = { path = "../../pallets/randomness", default_features = false }
simple-event = { path = "../../pallets/simple-event", default_features = false }
simple-map = { path = "../../pallets/simple-map", default-features = false }
single-value = { path = "../../pallets/single-value", default-features = false }
storage-cache = { path = "../../pallets/storage-cache", default-features = false }
struct-storage = { path = "../../pallets/struct-storage", default-features = false }
vec-set = { path = "../../pallets/vec-set", default-features = false }

# Other Substrate dependencies
frame-executive = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
frame-support = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
frame-system = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
sp-api = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
sp-block-builder = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
sp-consensus-babe = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
sp-core = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
sp-finality-grandpa = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
sp-inherents = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
sp-io = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
sp-offchain = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
sp-session = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
sp-transaction-pool = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
sp-version = { git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }


[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	# External dependencies
	"safe-mix/std",
	"parity-scale-codec/std",
	"serde",

	# Substrate dependencies alphabetically
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-finality-grandpa/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",

	# Substrate Pallets
	"babe/std",
	"balances/std",
	"grandpa/std",
	"randomness-collective-flip/std",
	"sudo/std",
	"timestamp/std",
	"transaction-payment/std",

	# Recipes pallets
	"adding-machine/std",
	"basic-token/std",
	"charity/std",
	"check-membership/std",
	"compounding-interest/std",
	"constant-config/std",
	"default-instance/std",
	"double-map/std",
	"execution-schedule/std",
	"fixed-point/std",
	"generic-event/std",
	"hello-substrate/std",
	"last-caller/std",
	"randomness/std",
	"ringbuffer-queue/std",
	"simple-event/std",
	"simple-map/std",
	"single-value/std",
	"storage-cache/std",
	"struct-storage/std",
	"vec-set/std",
]
