[package]
name = 'api-genesis'
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies.runtime]
package = 'api-runtime'
path = '../api-runtime'

[dependencies]
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", rev = 'ba5c85add52897acbd98f382ae11f7a11583e322' }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", rev = 'ba5c85add52897acbd98f382ae11f7a11583e322' }
