[package]
name = 'api-genesis'
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies.runtime]
package = 'api-runtime'
path = '../api-runtime'

[dependencies]
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", rev = '0bd9ffacdeb9bf3c97c04114de2cca5490ee98b6' }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", rev = '0bd9ffacdeb9bf3c97c04114de2cca5490ee98b6' }
