[package]
name = 'api-genesis'
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies.runtime]
package = 'api-runtime'
path = '../api-runtime'

[dependencies]
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", rev = '68e51d6e24862d499b5f042321cc87b172579e74' }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", rev = '68e51d6e24862d499b5f042321cc87b172579e74' }
