[package]
name = 'weight-fee-genesis'
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies.runtime]
package = 'weight-fee-runtime'
path = '../weight-fee-runtime'

[dependencies]
babe-primitives = { package = "sp-consensus-babe", git = "https://github.com/paritytech/substrate", rev = '68e51d6e24862d499b5f042321cc87b172579e74' }
grandpa-primitives = { package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate", rev = '68e51d6e24862d499b5f042321cc87b172579e74' }
