[package]
name = "kitchen-node"
version = "2.0.0"
authors = ["Anonymous"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "kitchen-node"
path = "src/main.rs"

[dependencies]
derive_more = "0.15.0"
futures = "0.3.1"
structopt = "0.3.8"
futures01 = { package = "futures", version = "0.1.29" }
ctrlc = { version = "3.1.3", features = ["termination"] }
log = "0.4.8"
tokio = "0.1.22"
exit-future = "0.2.0"
parking_lot = "0.9.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
trie-root = "0.15.2"
sp-io = { version = '2.0.0-alpha.5' }
sc-cli = { version = '0.8.0-alpha.5' }
sc-client-api = { version = '2.0.0-alpha.5' }
sp-core = { version = '2.0.0-alpha.5' }
sp-runtime = { version = '2.0.0-alpha.5' }
sc-executor = { version = '0.8.0-alpha.5' }
sc-service = { version = '0.8.0-alpha.5' }
sp-inherents = { version = '2.0.0-alpha.5' }
sc-transaction-pool = { version = '2.0.0-alpha.5' }
sp-transaction-pool = { version = '2.0.0-alpha.5' }
sc-network = { version = '0.8.0-alpha.5' }
sc-consensus-babe = { version = '0.8.0-alpha.5' }
sp-consensus-babe = { version = '0.8.0-alpha.5' }
sc-finality-grandpa = { version = '0.8.0-alpha.5' }
sp-finality-grandpa = { version = '2.0.0-alpha.5' }
sc-client = { version = '0.8.0-alpha.5' }
sc-basic-authorship = { version = '0.8.0-alpha.5' }
sp-consensus = { version = '0.8.0-alpha.5' }

# Pick one of the runtimes below.
# Your runtime must have the necessary pallets to support consensus (Babe, Grandpa, etc).
# ---
# Common runtime configured with most Recipes pallets.
runtime = { package = "super-runtime", path = "../../runtimes/super-runtime" }

# Runtime with custom weight and fee calculation.
# runtime = { package = "weight-fee-runtime", path = "../../runtimes/weight-fee-runtime"}

# Runtime with off-chain worker enabled.
# To use this runtime, compile kitchen-node with `ocw` feature enabled,
#   `cargo build --release --features ocw`.
# runtime = { package = "ocw-runtime", path = "../../runtimes/ocw-runtime" }

# TODO Can't use this until the API runtime implements babe api
# runtime = { package = "api-runtime", path = "../../runtimes/api-runtime" }
# ---

[build-dependencies]
vergen = "3.0.4"
substrate-build-script-utils = '2.0.0-alpha.5'

[features]
ocw = []
