[package]
name = 'rpc-node'
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
build = 'build.rs'
edition = '2018'
version = "2.0.0-rc6"
repository = 'https://github.com/substrate-developer-hub/recipes'
description = "A Substrate node that demonstrates a custom RPC endpoint"
license = "GPL-3.0-or-later"

[package.metadata.substrate]
categories = [
	"Node",
	"Custom RPC",
	"tutorial",
	"Instant Seal",
	"recipe",
]
compatibility_version = "2.0.0-rc6"

[[bin]]
name = 'rpc-node'
path = 'src/main.rs'

[dependencies]
futures = '0.3.1'
log = '0.4.8'
parking_lot = '0.9.0'
tokio = '0.1.22'
trie-root = '0.15.2'
structopt = "0.3.8"
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
ctrlc = { features = ['termination'], version = '3.1.3' }
futures01 = { package = 'futures', version = '0.1.29'}
sc-rpc = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sc-rpc-api = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sc-client-api = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sum-storage-rpc = { path = "../../pallets/sum-storage/rpc" }
sum-storage-runtime-api = { path = "../../pallets/sum-storage/runtime-api" }
sc-basic-authorship = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sc-cli = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sc-consensus = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sc-consensus-manual-seal = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sc-executor = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sc-network = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sc-service = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sc-transaction-pool = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sp-block-builder = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sp-blockchain = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sp-consensus = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sp-core = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sp-inherents = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sp-io = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sp-timestamp = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sp-transaction-pool = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
sp-api = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }

# RPC Node only works with Runtime's that provide the sum-storage-runtime-api
# That means it only works with the api-runtime
runtime = { package = "api-runtime", path = "../../runtimes/api-runtime" }

[build-dependencies]
vergen = '3.0.4'
substrate-build-script-utils = { git = 'https://github.com/paritytech/substrate.git', branch = 'joshy-split-manual-seal-finality' }
