[package]
authors = ['Anonymous']
build = 'build.rs'
edition = '2018'
name = 'rpc-node'
version = '2.0.0'

[[bin]]
name = 'rpc-node'
path = 'src/main.rs'

[dependencies]
futures = '0.3.1'
log = '0.4.8'
parking_lot = '0.9.0'
tokio = '0.1.22'
trie-root = '0.15.2'
structopt = "0.3.8"
runtime = { package = "api-runtime", path = "../../runtimes/api-runtime" }
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
sc-rpc = { version = '2.0.0-alpha.5' }
sc-client-api = { version = '2.0.0-alpha.5' }
sum-storage-rpc = { path = "../../pallets/sum-storage/rpc" }

[dependencies.codec]
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.ctrlc]
features = ['termination']
version = '3.1.3'

[dependencies.futures01]
package = 'futures'
version = '0.1.29'

[dependencies.grandpa]

package = 'sc-finality-grandpa'
version = '0.8.0-alpha.5'

[dependencies.grandpa-primitives]

package = 'sp-finality-grandpa'
version = '2.0.0-alpha.5'

[dependencies.sc-basic-authorship]

version = '0.8.0-alpha.5'

[dependencies.sc-cli]
version = '0.8.0-alpha.5'

[dependencies.sc-client]

version = '0.8.0-alpha.5'

[dependencies.sc-consensus-aura]

version = '0.8.0-alpha.5'

[dependencies.sc-executor]

version = '0.8.0-alpha.5'

[dependencies.sc-network]

version = '0.8.0-alpha.5'

[dependencies.sc-service]

version = '0.8.0-alpha.5'

[dependencies.sc-transaction-pool]

version = '2.0.0-alpha.5'

[dependencies.sp-consensus]

version = '0.8.0-alpha.5'

[dependencies.sp-consensus-aura]

version = '0.8.0-alpha.5'

[dependencies.sp-core]

version = '2.0.0-alpha.5'

[dependencies.sp-inherents]

version = '2.0.0-alpha.5'

[dependencies.sp-io]

version = '2.0.0-alpha.5'

[dependencies.sp-runtime]

version = '2.0.0-alpha.5'

[dependencies.sp-transaction-pool]

version = '2.0.0-alpha.5'



[build-dependencies]
vergen = '3.0.4'
substrate-build-script-utils = '2.0.0-alpha.5'
