[package]
name = "basic-token"
version = "0.1.0"
authors = ["4meta5"]
edition = "2018"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
]

[dependencies]
parity-scale-codec = { version = "1.1.0", features = ["derive"], default-features = false }
frame-support = { rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630', git = "https://github.com/paritytech/substrate.git", default_features = false }
frame-system = { rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630', git = "https://github.com/paritytech/substrate.git", default_features = false }

[dev-dependencies]
sp-core = { rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630', git = "https://github.com/paritytech/substrate.git", default_features = false }
sp-io = { rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630', git = "https://github.com/paritytech/substrate.git", default_features = false }
sp-runtime = { rev = '34c5cb3f66ba47cea6c50aefbf24d35cbf742630', git = "https://github.com/paritytech/substrate.git", default_features = false }
