[build-dependencies]
vergen = '3.0.4'
substrate-build-script-utils = '2.0.0-alpha.5'

[package]
authors = ['Anonymous']
build = 'build.rs'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'basic-pow'
repository = 'https://github.com/paritytech/substrate/'
version = "2.0.0"

[[bin]]
name = 'basic-pow'
path = 'src/main.rs'

[dependencies]
futures = '0.3.1'
log = '0.4.8'
structopt = '0.3.8'
parity-scale-codec = '1.0.0'
sha3 = "0.8"
rand = { version = "0.7", features = ["small_rng"] }
sc-consensus-pow = { version = '0.8.0-alpha.5' }
sp-consensus-pow = { version = '0.8.0-alpha.5' }
sc-client-api = { version = '2.0.0-alpha.5' }
sp-blockchain = { version = '2.0.0-alpha.5' }
runtime = { package = "pow-runtime", path = "../../runtimes/pow-runtime" }

[dependencies.sp-timestamp]

version = '2.0.0-alpha.5'

[dependencies.sc-basic-authorship]
version = '0.8.0-alpha.5'

[dependencies.sc-cli]

version = '0.8.0-alpha.5'

[dependencies.sc-client]
version = '0.8.0-alpha.5'

[dependencies.sc-executor]

version = '0.8.0-alpha.5'

[dependencies.sc-network]

version = '0.8.0-alpha.5'

[dependencies.sc-service]

version = '0.8.0-alpha.5'

[dependencies.sc-transaction-pool]

version = '2.0.0-alpha.5'

[dependencies.sp-consensus]

version = '0.8.0-alpha.5'

[dependencies.sp-core]

version = '2.0.0-alpha.5'

[dependencies.sp-inherents]

version = '2.0.0-alpha.5'

[dependencies.sp-runtime]

version = '2.0.0-alpha.5'

[dependencies.sp-transaction-pool]

version = '2.0.0-alpha.5'
