[build-dependencies]
vergen = '3.0.4'

[build-dependencies.build-script-utils]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-build-script-utils'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[package]
authors = ['Anonymous']
build = 'build.rs'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'basic-pow'
repository = 'https://github.com/paritytech/substrate/'
version = "2.0.0"

[[bin]]
name = 'basic-pow'
path = 'src/main.rs'

[dependencies]
futures = '0.3.1'
log = '0.4.8'
structopt = '0.3.8'
parity-scale-codec = '1.0.0'
sha3 = "0.8"
rand = { version = "0.7", features = ["small_rng"] }
sc-consensus-pow = { git = "https://github.com/paritytech/substrate", rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1' }
sp-consensus-pow = { git = "https://github.com/paritytech/substrate", rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1' }
sc-client-api = { git = "https://github.com/paritytech/substrate", rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1' }
sp-blockchain = { git = "https://github.com/paritytech/substrate", rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1' }

runtime = { package = "pow-runtime", path = "../../runtimes/pow-runtime" }
runtime-genesis = { package = "pow-genesis", path = "../../runtimes/pow-genesis" }

# Attempt to use the babe inherent that the super-runtime expects. This hack didn't work.
# [dependencies.sp-consensus-babe]
# git = "https://github.com/paritytech/substrate"
# rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sp-timestamp]
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sc-basic-authorship]
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sc-cli]
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sc-client]
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sc-executor]
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sc-network]
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sc-service]
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sc-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sp-consensus]
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sp-core]
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sp-inherents]
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sp-runtime]
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sp-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'
