[package]
name = "single-value"
version = "0.1.0"
authors = ["4meta5"]
edition = "2018"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
]

[dependencies]
parity-scale-codec = { default-features = false, features = ['derive'], version = '1.0.6' }
frame-support = { git = 'https://github.com/paritytech/substrate.git', rev = 'ba5c85add52897acbd98f382ae11f7a11583e322',  default_features = false }
frame-system  = { git = 'https://github.com/paritytech/substrate.git', rev = 'ba5c85add52897acbd98f382ae11f7a11583e322',  default_features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', rev = 'ba5c85add52897acbd98f382ae11f7a11583e322',  default_features = false }

[dev-dependencies]
sp-core = { rev = 'ba5c85add52897acbd98f382ae11f7a11583e322', git = "https://github.com/paritytech/substrate.git", default_features = false }
sp-io = { rev = 'ba5c85add52897acbd98f382ae11f7a11583e322', git = "https://github.com/paritytech/substrate.git", default_features = false }
